// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: checker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStatus int32

const (
	CheckStatus_UNKNOWN  CheckStatus = 0
	CheckStatus_PENDING  CheckStatus = 1
	CheckStatus_CHECKING CheckStatus = 2
	CheckStatus_SUCCESS  CheckStatus = 3
	CheckStatus_FAILED   CheckStatus = 4
	CheckStatus_TIMEOUT  CheckStatus = 5
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "CHECKING",
		3: "SUCCESS",
		4: "FAILED",
		5: "TIMEOUT",
	}
	CheckStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"CHECKING": 2,
		"SUCCESS":  3,
		"FAILED":   4,
		"TIMEOUT":  5,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_proto_enumTypes[0].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_checker_proto_enumTypes[0]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{0}
}

type CheckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Config         string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CheckRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CheckRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CheckRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Status        CheckStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=checker.v1.CheckStatus" json:"status,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Protocol      string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Server        string                 `protobuf:"bytes,8,opt,name=server,proto3" json:"server,omitempty"`
	CountryCode   string                 `protobuf:"bytes,9,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CheckResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CheckResponse) GetStatus() CheckStatus {
	if x != nil {
		return x.Status
	}
	return CheckStatus_UNKNOWN
}

func (x *CheckResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *CheckResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CheckResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CheckResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CheckResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *CheckResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CheckResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_checker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ActiveWorkers int32                  `protobuf:"varint,3,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	QueueSize     int32                  `protobuf:"varint,4,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_checker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *HealthResponse) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_checker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{4}
}

type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalChecks      int64                  `protobuf:"varint,1,opt,name=total_checks,json=totalChecks,proto3" json:"total_checks,omitempty"`
	SuccessfulChecks int64                  `protobuf:"varint,2,opt,name=successful_checks,json=successfulChecks,proto3" json:"successful_checks,omitempty"`
	FailedChecks     int64                  `protobuf:"varint,3,opt,name=failed_checks,json=failedChecks,proto3" json:"failed_checks,omitempty"`
	SuccessRate      float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_checker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetTotalChecks() int64 {
	if x != nil {
		return x.TotalChecks
	}
	return 0
}

func (x *StatsResponse) GetSuccessfulChecks() int64 {
	if x != nil {
		return x.SuccessfulChecks
	}
	return 0
}

func (x *StatsResponse) GetFailedChecks() int64 {
	if x != nil {
		return x.FailedChecks
	}
	return 0
}

func (x *StatsResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *StatsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_checker_proto protoreflect.FileDescriptor

const file_checker_proto_rawDesc = "" +
	"\n" +
	"\rchecker.proto\x12\n" +
	"checker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\fCheckRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.checker.v1.CheckRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x02\n" +
	"\rCheckResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.checker.v1.CheckStatusR\x06status\x12\x19\n" +
	"\bis_valid\x18\x04 \x01(\bR\aisValid\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12\x16\n" +
	"\x06server\x18\b \x01(\tR\x06server\x12!\n" +
	"\fcountry_code\x18\t \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x0f\n" +
	"\rHealthRequest\"\x89\x02\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eactive_workers\x18\x03 \x01(\x05R\ractiveWorkers\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x04 \x01(\x05R\tqueueSize\x12A\n" +
	"\adetails\x18\x05 \x03(\v2'.checker.v1.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fStatsRequest\"\xce\x01\n" +
	"\rStatsResponse\x12!\n" +
	"\ftotal_checks\x18\x01 \x01(\x03R\vtotalChecks\x12+\n" +
	"\x11successful_checks\x18\x02 \x01(\x03R\x10successfulChecks\x12#\n" +
	"\rfailed_checks\x18\x03 \x01(\x03R\ffailedChecks\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds*[\n" +
	"\vCheckStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bCHECKING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x052\xda\x01\n" +
	"\rConfigChecker\x12G\n" +
	"\fCheckConfigs\x12\x18.checker.v1.CheckRequest\x1a\x19.checker.v1.CheckResponse(\x010\x01\x12?\n" +
	"\x06Health\x12\x19.checker.v1.HealthRequest\x1a\x1a.checker.v1.HealthResponse\x12?\n" +
	"\bGetStats\x12\x18.checker.v1.StatsRequest\x1a\x19.checker.v1.StatsResponseB(Z&github.com/NamiraNet/namira-core/protob\x06proto3"

var (
	file_checker_proto_rawDescOnce sync.Once
	file_checker_proto_rawDescData []byte
)

func file_checker_proto_rawDescGZIP() []byte {
	file_checker_proto_rawDescOnce.Do(func() {
		file_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checker_proto_rawDesc), len(file_checker_proto_rawDesc)))
	})
	return file_checker_proto_rawDescData
}

var file_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_checker_proto_goTypes = []any{
	(CheckStatus)(0),              // 0: checker.v1.CheckStatus
	(*CheckRequest)(nil),          // 1: checker.v1.CheckRequest
	(*CheckResponse)(nil),         // 2: checker.v1.CheckResponse
	(*HealthRequest)(nil),         // 3: checker.v1.HealthRequest
	(*HealthResponse)(nil),        // 4: checker.v1.HealthResponse
	(*StatsRequest)(nil),          // 5: checker.v1.StatsRequest
	(*StatsResponse)(nil),         // 6: checker.v1.StatsResponse
	nil,                           // 7: checker.v1.CheckRequest.MetadataEntry
	nil,                           // 8: checker.v1.HealthResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_checker_proto_depIdxs = []int32{
	7, // 0: checker.v1.CheckRequest.metadata:type_name -> checker.v1.CheckRequest.MetadataEntry
	0, // 1: checker.v1.CheckResponse.status:type_name -> checker.v1.CheckStatus
	9, // 2: checker.v1.CheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	8, // 3: checker.v1.HealthResponse.details:type_name -> checker.v1.HealthResponse.DetailsEntry
	1, // 4: checker.v1.ConfigChecker.CheckConfigs:input_type -> checker.v1.CheckRequest
	3, // 5: checker.v1.ConfigChecker.Health:input_type -> checker.v1.HealthRequest
	5, // 6: checker.v1.ConfigChecker.GetStats:input_type -> checker.v1.StatsRequest
	2, // 7: checker.v1.ConfigChecker.CheckConfigs:output_type -> checker.v1.CheckResponse
	4, // 8: checker.v1.ConfigChecker.Health:output_type -> checker.v1.HealthResponse
	6, // 9: checker.v1.ConfigChecker.GetStats:output_type -> checker.v1.StatsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_checker_proto_init() }
func file_checker_proto_init() {
	if File_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checker_proto_rawDesc), len(file_checker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checker_proto_goTypes,
		DependencyIndexes: file_checker_proto_depIdxs,
		EnumInfos:         file_checker_proto_enumTypes,
		MessageInfos:      file_checker_proto_msgTypes,
	}.Build()
	File_checker_proto = out.File
	file_checker_proto_goTypes = nil
	file_checker_proto_depIdxs = nil
}
